## Numpy data structures

When we looked at python data structures, it was obvious that the only way to deal with arrays of values (matrices / vectors etc) would be via lists and lists of lists.

This is slow and inefficient in both execution and writing code. 

`Numpy` attempts to fix this. 

In [ ]:
import numpy as np

## This is a list of everything in the module
np.__all__

In [ ]:
an_array = np.array([0,1,2,3,4,5,6])

print an_array
print
print type(an_array)
print
help(an_array)

In [ ]:
A = np.zeros((4,4))
print A
print
print A.shape
print
print A.diagonal()
print

A[0,0] = 2.0
print A

np.fill_diagonal(A, 1.0)
print A

B = A.diagonal()
B[0] = 2.0

In [ ]:
for i in range(0,A.shape[0]):
    A[i,i] = 1.0
print A
print

A[:,2] = 2.0
print A
print

A[2,:] = 4.0
print A
print

print A.T
print

A[...] = 0.0
print A
print

for i in range(0,A.shape[0]):
    A[i,:] = float(i)
    
print A
print

for i in range(0,A.shape[0]):
    A[i,:] = i
    
print A
print

print A[::2,::2] 
print

print A[::-1,::-1]

## Speed

In [ ]:
%%timeit

B = np.zeros((1000,1000))
for i in range(0,1000):
    for j in range(0,1000):
        B[i,j] = 2.0
        
        

In [ ]:
%%timeit

B = np.zeros((1000,1000))
B[:,:] = 2.0

In [ ]:
%%timeit

B = np.zeros((1000,1000))
B[...] = 2.0

## Views of the data (are free)

It costs very little to look at data in a different way (e.g. to view a 2D array as a 1D vector).

Making a copy is a different story

In [ ]:
print A.reshape((2,8))
print

print A.reshape((-1))
print A.ravel()
print

print A.reshape((1,-1))
print

In [ ]:
%%timeit 

A.reshape((1,-1))

In [ ]:
%%timeit

elements = A.shape[0]*A.shape[1]
B = np.empty(elements)
B[...] = A[:,:].ravel()


In [ ]:
%%timeit

elements = A.shape[0]*A.shape[1]
B = np.empty(elements)

for i in range(0,A.shape[0]):
    for j in range(0,A.shape[1]):
        B[i+j*A.shape[1]] = A[i,j]


__Exercise:__ Try this again for a 10000x10000 array

## Vector Operations


In [ ]:
X = np.arange(0.0, 2.0*np.pi, 0.0001)

In [ ]:
print X[0:100]

In [ ]:
import math

math.sin(X)

In [ ]:
np.sin(X)

In [ ]:
S = np.sin(X)
C = np.cos(X)

In [ ]:
S2 =  S**2 + C**2
print S2

In [ ]:
print S2 - 1.0

In [ ]:
test = np.isclose(S2,1.0)
print test

In [ ]:
print np.where(test == False)
print np.where(S2 == 0.0)

---

__Exercise__: find out how long it takes to compute the sin, sqrt, power of a 1000000 length vector (array). How does this speed compare to using the normal `math` functions element by element in the array ? What happens if X is actually a complex array ?

__Hints:__ you might find it useful to know about:
  - `np.linspace` v `np.arange`
  - `np.empty_like` or `np.zeros_like`
  - the python `enumerate` function
  - how to write a table in markdown
  
| description     | time   | notes |
|-----------------|--------|-------|
| `np.sin`        | ?      |       |
| `math.sin`      | ?      |       |
|                 | ?      |  -    |

In [ ]:
X = np.linspace(0.0, 2.0*np.pi, 10000000)
print X.shape

# ... 

In [ ]:
%%timeit
S = np.sin(X)

In [ ]:
%%timeit

S = np.empty_like(X)
for i, x in enumerate(X):
    S[i] = math.sin(x)
    

In [ ]:
X = np.linspace(0.0, 2.0*np.pi, 10000000)
Xj = X + 1.0j
print Xj.shape, Xj.dtype

In [ ]:
%%timeit

Sj = np.sin(Xj)

In [ ]:
import cmath

In [ ]:
%%timeit

Sj = np.empty_like(Xj)
for i, x in enumerate(Xj):
    Sj[i] = cmath.sin(x)
    

__Exercise__: look through the functions below from numpy, choose 3 of them and work out how to use them on arrays of data. Write a few lines to explain what you find. 

  - `np.max` v. `np.argmax`
  - `np.where`
  - `np.logical_and`
  - `np.fill_diagonal`
  - `np.count_nonzero`
  - `np.isinf` and `np.isnan`
  
  
Here is an example: 

`np.concatenate` takes a number of arrays and glues them together. For 1D arrays this is simple:

```python

A = np.array([1.0,1.0,1.0,1.0])
B = np.array([2.0,2.0,2.0,2.0])
C = np.array([3.0,3.0,3.0,3.0])

R = np.concatenate((A,B,C))

# array([ 1.,  1.,  1.,  1.,  2.,  2.,  2.,  2.,  3.,  3.,  3.,  3.])
```

an equivalent statement is `np.hstack((A,B,C))` but note the difference with `np.vstack((A,B,C))`

With higher dimensional arrays, the gluing takes place along one `axis`:

```python
A = np.array(([1.0,1.0,1.0,1.0],[2.0,2.0,2.0,2.0]))
B = np.array(([3.0,3.0,3.0,3.0],[4.0,4.0,4.0,4.0]))
C = np.array(([5.0,5.0,5.0,5.0],[6.0,6.0,6.0,6.0]))

R = np.concatenate((A,B,C))
print R
print
R = np.concatenate((A,B,C), axis=1)
print R

```


In [112]:
# Test the results here 

A = np.array(([1.0,1.0,1.0,1.0],[2.0,2.0,2.0,2.0]))
B = np.array(([3.0,3.0,3.0,3.0],[4.0,4.0,4.0,4.0]))
C = np.array(([5.0,5.0,5.0,5.0],[6.0,6.0,6.0,6.0]))

R = np.concatenate((A,B,C))
print R
print
R = np.concatenate((A,B,C), axis=1)
print R

[[ 1.  1.  1.  1.]
 [ 2.  2.  2.  2.]
 [ 3.  3.  3.  3.]
 [ 4.  4.  4.  4.]
 [ 5.  5.  5.  5.]
 [ 6.  6.  6.  6.]]

[[ 1.  1.  1.  1.  3.  3.  3.  3.  5.  5.  5.  5.]
 [ 2.  2.  2.  2.  4.  4.  4.  4.  6.  6.  6.  6.]]
