## Numpy data structures

When we looked at python data structures, it was obvious that the only way to deal with arrays of values (matrices / vectors etc) would be via lists and lists of lists.

This is slow and inefficient in both execution and writing code. 

`Numpy` attempts to fix this. 

In [2]:
import numpy as np

## This is a list of everything in the module
np.__all__

['add_newdocs',
 'ModuleDeprecationWarning',
 'VisibleDeprecationWarning',
 '__version__',
 'pkgload',
 'PackageLoader',
 'show_config',
 'char',
 'rec',
 'memmap',
 'newaxis',
 'ndarray',
 'flatiter',
 'nditer',
 'nested_iters',
 'ufunc',
 'arange',
 'array',
 'zeros',
 'count_nonzero',
 'empty',
 'broadcast',
 'dtype',
 'fromstring',
 'fromfile',
 'frombuffer',
 'int_asbuffer',
 'where',
 'argwhere',
 'copyto',
 'concatenate',
 'fastCopyAndTranspose',
 'lexsort',
 'set_numeric_ops',
 'can_cast',
 'promote_types',
 'min_scalar_type',
 'result_type',
 'asarray',
 'asanyarray',
 'ascontiguousarray',
 'asfortranarray',
 'isfortran',
 'empty_like',
 'zeros_like',
 'ones_like',
 'correlate',
 'convolve',
 'inner',
 'dot',
 'outer',
 'vdot',
 'alterdot',
 'restoredot',
 'roll',
 'rollaxis',
 'moveaxis',
 'cross',
 'tensordot',
 'array2string',
 'get_printoptions',
 'set_printoptions',
 'array_repr',
 'array_str',
 'set_string_function',
 'little_endian',
 'require',
 'fromiter',
 'array_equ

In [3]:
an_array = np.array([0,1,2,3,4,5,6])

print an_array
print
print type(an_array)
print
help(an_array)

[0 1 2 3 4 5 6]

<type 'numpy.ndarray'>

Help on ndarray object:

class ndarray(__builtin__.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  d

In [4]:
A = np.zeros((4,4))
print A
print
print A.shape
print
print A.diagonal()
print

A[0,0] = 2.0
print A

np.fill_diagonal(A, 1.0)
print A

B = A.diagonal()
B[0] = 2.0

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]

(4, 4)

[ 0.  0.  0.  0.]

[[ 2.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


ValueError: assignment destination is read-only

In [5]:
for i in range(0,A.shape[0]):
    A[i,i] = 1.0
print A
print

A[:,2] = 2.0
print A
print

A[2,:] = 4.0
print A
print

print A.T
print

A[...] = 0.0
print A
print

for i in range(0,A.shape[0]):
    A[i,:] = float(i)
    
print A
print

for i in range(0,A.shape[0]):
    A[i,:] = i
    
print A
print

print A[::2,::2] 
print

print A[::-1,::-1]

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]

[[ 1.  0.  2.  0.]
 [ 0.  1.  2.  0.]
 [ 0.  0.  2.  0.]
 [ 0.  0.  2.  1.]]

[[ 1.  0.  2.  0.]
 [ 0.  1.  2.  0.]
 [ 4.  4.  4.  4.]
 [ 0.  0.  2.  1.]]

[[ 1.  0.  4.  0.]
 [ 0.  1.  4.  0.]
 [ 2.  2.  4.  2.]
 [ 0.  0.  4.  1.]]

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]

[[ 0.  0.  0.  0.]
 [ 1.  1.  1.  1.]
 [ 2.  2.  2.  2.]
 [ 3.  3.  3.  3.]]

[[ 0.  0.  0.  0.]
 [ 1.  1.  1.  1.]
 [ 2.  2.  2.  2.]
 [ 3.  3.  3.  3.]]

[[ 0.  0.]
 [ 2.  2.]]

[[ 3.  3.  3.  3.]
 [ 2.  2.  2.  2.]
 [ 1.  1.  1.  1.]
 [ 0.  0.  0.  0.]]


## Speed

In [6]:
%%timeit

B = np.zeros((1000,1000))
for i in range(0,1000):
    for j in range(0,1000):
        B[i,j] = 2.0
        
        

10 loops, best of 3: 117 ms per loop


In [7]:
%%timeit

B = np.zeros((1000,1000))
B[:,:] = 2.0

1000 loops, best of 3: 843 µs per loop


In [8]:
%%timeit

B = np.zeros((1000,1000))
B[...] = 2.0

1000 loops, best of 3: 1.51 ms per loop


## Views of the data (are free)

It costs very little to look at data in a different way (e.g. to view a 2D array as a 1D vector).

Making a copy is a different story

In [9]:
print A.reshape((2,8))
print

print A.reshape((-1))
print A.ravel()
print

print A.reshape((1,-1))
print

[[ 0.  0.  0.  0.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  3.  3.  3.  3.]]

[ 0.  0.  0.  0.  1.  1.  1.  1.  2.  2.  2.  2.  3.  3.  3.  3.]
[ 0.  0.  0.  0.  1.  1.  1.  1.  2.  2.  2.  2.  3.  3.  3.  3.]

[[ 0.  0.  0.  0.  1.  1.  1.  1.  2.  2.  2.  2.  3.  3.  3.  3.]]



In [10]:
%%timeit 

A.reshape((1,-1))

The slowest run took 37.70 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 474 ns per loop


In [11]:
%%timeit

elements = A.shape[0]*A.shape[1]
B = np.empty(elements)
B[...] = A[:,:].ravel()


The slowest run took 10.71 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.49 µs per loop


In [12]:
%%timeit

elements = A.shape[0]*A.shape[1]
B = np.empty(elements)

for i in range(0,A.shape[0]):
    for j in range(0,A.shape[1]):
        B[i+j*A.shape[1]] = A[i,j]


The slowest run took 4.40 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 8.18 µs per loop


__Exercise:__ Try this again for a 10000x10000 array

## Indexing / broadcasting

In numpy, we can index an array by explicitly specifying elements, by specifying slices, by supplying lists of indices (or arrays), we can also supply a boolean array of the same shape as the original array which will select / return an array of all those entries where `True` applies.

Although some of these might seem difficult to use, they are often the result of other numpy operations. For example `np.where` converts a truth array to a list of indices.

In [18]:
AA = np.zeros((100,100))

AA[10,11] = 1.0
AA[99,1]  = 2.0

cond = np.where(AA >= 1.0)
print cond
print AA[cond]
print AA[ AA >= 1]

(array([10, 99]), array([11,  1]))
[ 1.  2.]
[ 1.  2.]


---

Broadcasting is a way of looping on arrays which have "compatible" but unequal sizes.

For example, the element-wise multiplication of 2 arrays

```python
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0]) 
print a * b
```
has an equivalent:

```python
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0]) 
print a * b
```

or 

```python
a = np.array([1.0, 2.0, 3.0])
b = 2.0 
print a * b
```

in which the "appropriate" interpretation of `b` is made in each case to achieve the result. 

In [20]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0]) 

print a * b

b = np.array([2.0]) 

print a * b
print a * 2.0

[ 2.  4.  6.]
[ 2.  4.  6.]
[ 2.  4.  6.]


Arrays are compatible as long as each of their dimensions (shape) is either equal to the other or 1. 

Thus, above, the multplication works when `a.shape` is `(1,3)` and `b.shape` is either `(1,3)` or `(1,1)`

(Actually, these are `(3,)` and `(1,)` in the examples above ... 

In [41]:
print a.shape
print b.shape
print (a*b).shape
print (a+b).shape


aa = a.reshape(1,3)
bb = b.reshape(1,1)

print aa.shape
print bb.shape
print (aa*bb).shape
print (aa+bb).shape

(3,)
(1,)
(3,)
(3,)
(1, 3)
(1, 1)
(1, 3)
(1, 3)


In multiple dimensions, the rule applies but, perhaps, is less immediately intuitive:


In [50]:
a = np.array([[ 0.0, 0.0, 0.0],
              [10.0,10.0,10.0],
              [20.0,20.0,20.0],
              [30.0,30.0,30.0]])
b = np.array([[1.0,2.0,3.0]])
print a + b
print
print a.shape
print b.shape
print (a+b).shape

[[  1.   2.   3.]
 [ 11.  12.  13.]
 [ 21.  22.  23.]
 [ 31.  32.  33.]]

(4, 3)
(1, 3)
(4, 3)


Note that this also works for 

In [52]:
a = np.array([[ 0.0, 0.0, 0.0],
              [10.0,10.0,10.0],
              [20.0,20.0,20.0],
              [30.0,30.0,30.0]])

b = np.array([1.0,2.0,3.0])
print a + b
print
print a.shape
print b.shape
print (a+b).shape

[[  1.   2.   3.]
 [ 11.  12.  13.]
 [ 21.  22.  23.]
 [ 31.  32.  33.]]

(4, 3)
(3,)
(4, 3)
[[ 1.]
 [ 2.]
 [ 3.]]


But not for 

In [56]:
a = np.array([[ 0.0, 0.0, 0.0],
              [10.0,10.0,10.0],
              [20.0,20.0,20.0],
              [30.0,30.0,30.0]])

b = np.array([[1.0],[2.0],[3.0]])

print a.shape
print b.shape
print (a+b).shape

(4, 3)
(3, 1)


ValueError: operands could not be broadcast together with shapes (4,3) (3,1) 

## Vector Operations


In [ ]:
X = np.arange(0.0, 2.0*np.pi, 0.0001)

In [ ]:
print X[0:100]

In [ ]:
import math

math.sin(X)

In [ ]:
np.sin(X)

In [ ]:
S = np.sin(X)
C = np.cos(X)

In [ ]:
S2 =  S**2 + C**2
print S2

In [ ]:
print S2 - 1.0

In [ ]:
test = np.isclose(S2,1.0)
print test

In [ ]:
print np.where(test == False)
print np.where(S2 == 0.0)

---

__Exercise__: find out how long it takes to compute the sin, sqrt, power of a 1000000 length vector (array). How does this speed compare to using the normal `math` functions element by element in the array ? What happens if X is actually a complex array ?

__Hints:__ you might find it useful to know about:
  - `np.linspace` v `np.arange`
  - `np.empty_like` or `np.zeros_like`
  - the python `enumerate` function
  - how to write a table in markdown
  
| description     | time   | notes |
|-----------------|--------|-------|
| `np.sin`        | ?      |       |
| `math.sin`      | ?      |       |
|                 | ?      |  -    |

In [ ]:
X = np.linspace(0.0, 2.0*np.pi, 10000000)
print X.shape

# ... 

In [ ]:
%%timeit
S = np.sin(X)

In [ ]:
%%timeit

S = np.empty_like(X)
for i, x in enumerate(X):
    S[i] = math.sin(x)
    

In [ ]:
X = np.linspace(0.0, 2.0*np.pi, 10000000)
Xj = X + 1.0j
print Xj.shape, Xj.dtype

In [ ]:
%%timeit

Sj = np.sin(Xj)

In [ ]:
import cmath

In [ ]:
%%timeit

Sj = np.empty_like(Xj)
for i, x in enumerate(Xj):
    Sj[i] = cmath.sin(x)
    

__Exercise__: look through the functions below from numpy, choose 3 of them and work out how to use them on arrays of data. Write a few lines to explain what you find. 

  - `np.max` v. `np.argmax`
  - `np.where`
  - `np.logical_and`
  - `np.fill_diagonal`
  - `np.count_nonzero`
  - `np.isinf` and `np.isnan`
  
  
Here is an example: 

`np.concatenate` takes a number of arrays and glues them together. For 1D arrays this is simple:

```python

A = np.array([1.0,1.0,1.0,1.0])
B = np.array([2.0,2.0,2.0,2.0])
C = np.array([3.0,3.0,3.0,3.0])

R = np.concatenate((A,B,C))

# array([ 1.,  1.,  1.,  1.,  2.,  2.,  2.,  2.,  3.,  3.,  3.,  3.])
```

an equivalent statement is `np.hstack((A,B,C))` but note the difference with `np.vstack((A,B,C))`

With higher dimensional arrays, the gluing takes place along one `axis`:

```python
A = np.array(([1.0,1.0,1.0,1.0],[2.0,2.0,2.0,2.0]))
B = np.array(([3.0,3.0,3.0,3.0],[4.0,4.0,4.0,4.0]))
C = np.array(([5.0,5.0,5.0,5.0],[6.0,6.0,6.0,6.0]))

R = np.concatenate((A,B,C))
print R
print
R = np.concatenate((A,B,C), axis=1)
print R

```


In [112]:
# Test the results here 

A = np.array(([1.0,1.0,1.0,1.0],[2.0,2.0,2.0,2.0]))
B = np.array(([3.0,3.0,3.0,3.0],[4.0,4.0,4.0,4.0]))
C = np.array(([5.0,5.0,5.0,5.0],[6.0,6.0,6.0,6.0]))

R = np.concatenate((A,B,C))
print R
print
R = np.concatenate((A,B,C), axis=1)
print R

[[ 1.  1.  1.  1.]
 [ 2.  2.  2.  2.]
 [ 3.  3.  3.  3.]
 [ 4.  4.  4.  4.]
 [ 5.  5.  5.  5.]
 [ 6.  6.  6.  6.]]

[[ 1.  1.  1.  1.  3.  3.  3.  3.  5.  5.  5.  5.]
 [ 2.  2.  2.  2.  4.  4.  4.  4.  6.  6.  6.  6.]]
